language: python
python:
  - "3.6"

addons:
  ssh_known_hosts:
  - $SERVER_HOST

before_install:
- openssl aes-256-cbc -K $encrypted_681dc6bc9314_key -iv $encrypted_681dc6bc9314_iv
  -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa

install: "pip install -r requirements.txt"

script: python manage.py test

after_success:
- mkdir build
- cd ..
- tar -czf build.tgz *
- scp -i ~/.ssh/id_rsa -o stricthostkeychecking=no build.tgz $DEPLOY_USERNAME@$DEPLOY_HOST:$DEPLOY_PATH
